import { build } from 'esbuild';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {codecNotices} from './codec_notices.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const notices=await codecNotices(root);
const result=await build({entryPoints:[path.join(root,'studio/web/delivery.js')],bundle:true,write:false,minify:true,format:'iife',target:'es2022',define:{'import.meta.url':JSON.stringify('https://studio.invalid/bundled/module.js')},alias:{'three/addons':path.join(root,'studio/web/vendor/addons'),three:path.join(root,'studio/web/vendor/three.module.js')}});
// Static text carries data-i18n hooks (studio/web/i18n.js is bundled through delivery.js); the Chinese stays as the pre-hydration default.
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title data-i18n="delivery.template.title">3D 成果</title><style>*{box-sizing:border-box}body{margin:0;background:#111821;color:#dce5ef;font-family:system-ui,sans-serif}header{height:76px;display:flex;align-items:center;justify-content:space-between;padding:18px 26px;gap:20px;border-bottom:1px solid #334050}h1{font-size:20px;font-weight:550}button,select{padding:8px 12px;border:1px solid #44556a;border-radius:6px;background:#202d40;color:inherit;margin-left:6px}#stage{height:calc(100vh - 140px)}canvas{display:block;width:100%;height:100%}footer{padding:14px 26px;font-size:12px;color:#98acc4}#detail{margin-left:20px;color:#dce5ef}[hidden]{display:none!important}</style>${notices}</head><body><header><h1></h1><div><select id="asset" aria-label="模型" data-i18n-attr="aria-label=delivery.template.assetAriaLabel" hidden><option value="-1" data-i18n="delivery.template.allModels">全部模型</option></select><select id="clip" hidden></select><button id="play" data-i18n="delivery.action.play" hidden>播放动作</button><button id="explore" data-i18n="delivery.explore.enter">WASD 漫游</button><button id="fit" data-i18n="editor.tool.fitView">适配视图</button></div></header><main id="stage"></main><footer><span id="status" data-i18n="delivery.template.opening">正在打开模型…</span><span id="detail"></span></footer><script type="application/json" id="project-data">__WORKBENCH_PROJECT_DATA__</script><script>${result.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></body></html>`;
await mkdir(path.join(root,'studio/app/dist'),{recursive:true});await writeFile(path.join(root,'studio/app/dist/delivery.html'),html);
console.log('Built offline 3D delivery template',Buffer.byteLength(html));
