#!/usr/bin/env python3
"""Generate ``docs/TOOLS.md``, the reference of every MCP tool this plugin exposes.

The tool list is assembled the same way the stdio MCP server assembles it
(``studio.shell.mcp_server._tool_list``), so the document can never disagree with what Codex
actually sees. Run ``make tools-doc`` after changing any ``*_schema.py`` file or
``studio/shell/mcp_server.py``; ``--check`` exits non-zero when the committed file is stale.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

_PLUGIN_ROOT = Path(__file__).resolve().parent.parent
if str(_PLUGIN_ROOT) not in sys.path:
    sys.path.insert(0, str(_PLUGIN_ROOT))

from studio.shell import mcp_server, tools_schema  # noqa: E402

OUTPUT = _PLUGIN_ROOT / "docs" / "TOOLS.md"
COMMON_PARAM = "workspace_id"


def _md_cell(text: Any) -> str:
    return str(text if text is not None else "").replace("|", "\\|").replace("\n", " ").strip()


def _type_of(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    kind = schema.get("type", "any")
    if kind == "array":
        inner = schema.get("items", {}).get("type", "any")
        return f"array of {inner}"
    return str(kind)


def _params_table(input_schema: dict[str, Any]) -> list[str]:
    props: dict[str, Any] = input_schema.get("properties", {})
    required = set(input_schema.get("required", []))
    rows = [
        "| Parameter | Type | Required | Description |",
        "|---|---|---|---|",
    ]
    for name, schema in props.items():
        if name == COMMON_PARAM:
            continue
        default = schema.get("default")
        desc = _md_cell(schema.get("description", ""))
        if default is not None:
            desc = f"{desc} (default `{default}`)".strip()
        rows.append(f"| `{name}` | {_type_of(schema)} | {'yes' if name in required else 'no'} | {desc} |")
    if len(rows) == 2:
        return ["_No parameters besides the common `workspace_id`._"]
    return rows


def render() -> str:
    by_name = {t["name"]: t for t in tools_schema.get_tools()}
    tools = mcp_server._tool_list()
    lines = [
        "# MCP tool reference",
        "",
        "<!-- Generated by scripts/gen_tool_reference.py. Do not edit by hand: run `make tools-doc`. -->",
        "",
        f"This plugin registers **{len(tools)} tools** on its stdio MCP server. Every tool accepts the",
        f"common parameter `{COMMON_PARAM}` (the current Codex task ID, see `skills/`), omitted from the",
        "tables below. Tools marked *HTTP-backed* are thin wrappers over a route of the local backend",
        "(`studio/shell/server.py`) and are also reachable from the browser UI through WebMCP; the others are",
        "implemented directly in `studio/shell/mcp_server.py`.",
        "",
        "## Index",
        "",
        "| Tool | Read-only | Backend | Summary |",
        "|---|---|---|---|",
    ]
    for tool in tools:
        entry = by_name.get(tool.name)
        backend = f"HTTP `{entry['method']} {entry['path']}`" if entry else "MCP server"
        read_only = "yes" if (tool.annotations and tool.annotations.read_only_hint) else "no"
        summary = _md_cell((tool.description or "").split("。")[0].split(". ")[0])[:90]
        lines.append(f"| [`{tool.name}`](#{tool.name.replace('_', '')}) | {read_only} | {backend} | {summary} |")
    lines.append("")
    lines.append("## Tools")
    for tool in tools:
        entry = by_name.get(tool.name)
        lines += ["", f"### {tool.name}", ""]
        if tool.title:
            lines.append(f"**{_md_cell(tool.title)}**  ")
        if entry:
            lines.append(f"HTTP-backed: `{entry['method']} {entry['path']}`  ")
        lines.append("Read-only: " + ("yes" if (tool.annotations and tool.annotations.read_only_hint) else "no"))
        lines += ["", (tool.description or "").strip(), ""]
        lines += _params_table(tool.input_schema)
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if docs/TOOLS.md is out of date")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(_PLUGIN_ROOT)} is stale; run `make tools-doc`", file=sys.stderr)
            return 1
        print("docs/TOOLS.md is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(_PLUGIN_ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
